set shell=/bin/bash
if has('vim_starting')
  set nocompatible
endif

let statusPluginDirectory=system("if find ~/.vim/plugged/ -maxdepth 0 -empty | read v; then echo -n 'Empty dir'; fi")
if empty(glob('~/.vim/autoload/plug.vim')) || empty(glob('~/.vim/plugged/')) || statusPluginDirectory == "Empty dir"
  " Scenarios 1) the plug.vim script is not present,
  "           2) the plugged directory is not present,
  "           3) the plugged directory is present but empty (no files/directories within)
  "https://www.reddit.com/r/vim/comments/2tcm94/one_liner_to_bootstrap_vimplug/
  sil !wget -nc -q github.com/junegunn/vim-plug/raw/master/plug.vim -P ~/.vim/autoload/
  autocmd VimEnter * PlugInstall
endif

call plug#begin()

Plug 'airblade/vim-gitgutter'
Plug 'bitc/vim-bad-whitespace'
Plug 'bling/vim-airline'
Plug 'ctrlpvim/ctrlp.vim', { 'on': 'CtrlP' }
Plug 'flazz/vim-colorschemes'
Plug 'jistr/vim-nerdtree-tabs'
Plug 'mhinz/vim-startify'
Plug 'myusuf3/numbers.vim'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/nerdtree'
Plug 'sheerun/vim-polyglot'
Plug 'Shougo/neomru.vim'
Plug 'Shougo/vimproc.vim', { 'do': 'make' }
Plug 'Shougo/vimshell.vim'
Plug 'Shougo/unite.vim'
Plug 'terryma/vim-expand-region'
Plug 'terryma/vim-smooth-scroll'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'
Plug 'Xuyuanp/nerdtree-git-plugin'

call plug#end()

" Switch colon and semi-colon
nnoremap ; :
nnoremap : ;
vnoremap ; :
vnoremap : ;

" Move cursor by line naturally with k and j in navigation mode.
nnoremap j gj
nnoremap k gk

let mapleader = ","

" Don't automatically add newline to end of file
set binary noeol

" turn ON line numbers
set number

" 4 space softabs default
set expandtab
set ts=2
set sw=2

" Tabs
set autoindent            " copy indent from previous line
set expandtab             " replace tabs with spaces
set shiftwidth=2          " spaces for autoindenting
set smarttab              " <BS> removes shiftwidth worth of spaces
set softtabstop=2         " spaces for editing, e.g. <Tab> or <BS>
set tabstop=2             " spaces for <Tab>

" Automatic indentation
set autoindent
set smarttab

" quiet pls
set noeb vb t_vb=

syntax on
colorscheme zenburn "Tomorrow-Night-Eighties

" For nerdtree
let NERDTreeShowHidden=1

set hidden

" Backspace and cursor keys wrap
set whichwrap+=<,>,h,l

" Case insensitive matching.
set ignorecase

set showmatch

" Path/file expansion in colon-mode.
set wildmode=longest:full,list:full,list:longest
set wildchar=<TAB>

" How many lines of history to remember
set history=1000

" Space it out a little more (easier to read)
set lsp=0

" Use mouse everywhere
set mouse=a

" Open where I left off
set viminfo='1000,\"1000,:20,%,n~/.viminfo
au BufReadPost * if line("'\"") > 0|if line("'\"") <= line("$")|exe("norm '\"")|else|exe "norm $"|endif|endif

let g:ctrlp_show_hidden = 1
set wildignore+=*.class

set paste

" Clipboard sharing http://vim.wikia.com/wiki/Accessing_the_system_clipboard
set clipboard=unnamed

" Unite bindings http://www.reinteractive.net/posts/166-awesome-vim-plugins
nnoremap <silent> <Leader>r :Unite -buffer-name=recent -winheight=10 file_mru<cr>
nnoremap <Leader>b :Unite -quick-match buffer<cr>
nnoremap <Leader>f :Unite grep:.<cr>
nnoremap <Leader>nt :NERDTreeToggle<cr>
nnoremap <leader>nf :NERDTreeFind<cr>
nnoremap <leader>p :CtrlP<cr>

map <leader>/ <plug>NERDCommenterToggle
imap <leader>/ <Esc><plug>NERDCommenterTogglei

" easier navigation between split windows
nnoremap <C-J> <C-W>j
nnoremap <C-K> <C-W>k
nnoremap <C-H> <C-W>h
nnoremap <C-L> <C-W>l

set backspace=2 " make backspace work like most other apps

let g:nerdtree_tabs_open_on_console_startup=1

noremap <silent> <c-u> :call smooth_scroll#up(&scroll, 0, 2)<CR>
noremap <silent> <c-d> :call smooth_scroll#down(&scroll, 0, 2)<CR>
noremap <silent> <c-b> :call smooth_scroll#up(&scroll*2, 0, 4)<CR>
noremap <silent> <c-f> :call smooth_scroll#down(&scroll*2, 0, 4)<CR>

" http://vimrcfu.com/snippet/77
" Move visual block
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv
